name: keeper
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  path: ^1.8.0
#  path_provider: ^2.0.2
  dio: ^4.0.0
  web_socket_channel: ^2.1.0
  encrypt: ^5.0.1
  cryptography: ^2.0.2
  hive: ^2.0.4
#  hive_flutter: ^1.1.0
  image: ^3.0.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
